assert "MAX_RAM_MB" in config, "'MAX_RAM_MB' not in config"
MAX_RAM_MB = config["MAX_RAM_MB"]

include: "utils.py"

SEARCHES = []

wildcard_constraints:
    translation_mode = "start_to_stop|stop_to_stop",
    data_type =  "DDA|DIA"


class AntigeneSearch:
    def __init__(
                    self,
                    project,               # name of the run
                    hla_txt,               # path to HLA alleles text file (also hardcoded)
                    immunopeptidomics_data,               # path to the directory with immunopeptidomics data (also hardcoded)
                    input_fasta=None,        # nt fasta (optional if aa_fasta given)
                    input_aa_fasta=None,     # pre-translated aa fasta (optional). For example ORFs called from Riboseq
                    translation_mode='start_to_stop',
                    data_type='DDA',    #immunopeptidomics spectral  data  type. For reasons unknown to me, DIA  only accepts .mzML format
                    fdr_for_ip=0.01,               #the default FDR value is 1%
                    grouped_fdr=True
                ):
        assert (input_fasta is None) != (input_aa_fasta is None), \
            f"[{project}] Provide exactly one of input_fasta (nt) or input_aa_fasta (aa)"
        self.project = project
        self.hla_txt = hla_txt
        self.immunopeptidomics_data = immunopeptidomics_data
        self.input_fasta = input_fasta
        self.input_aa_fasta = input_aa_fasta
        self.translation_mode = translation_mode
        self.data_type = data_type
        self.fdr_for_ip = fdr_for_ip
        self.grouped_fdr = ' --group' if grouped_fdr else ''


def get_search(project):
    for search in SEARCHES:
        if search.project == project:
            return search
    raise ValueError(f"No search found for project '{project}'")


include: f"profiles/{config['todo']}/todo.py"

rule all:
    input:
        database_for_msfragger = [
            f"_data/antigene_search/{search.project}/final_msfragger_database.{search.project}.{search.translation_mode}.fasta"
            for search in SEARCHES
        ],
        xls = [
            f"_data/antigene_search/{search.project}/fragpipe_postprocessing/{search.project}.{search.translation_mode}.NetMHCpan_out.xls"
            for search in SEARCHES
        ],
        csv = [
            f"_data/antigene_search/{search.project}/fragpipe_postprocessing/Summary.{search.project}.{search.translation_mode}.csv"
            for search in SEARCHES
        ]


rule fix_fasta_header:
    input:
        input_fasta = lambda wildcards: get_search(wildcards.project).input_fasta
    output:
        input_fasta_fixed = "_data/antigene_search/{project}/{project}.fixed.fasta"
    benchmark: "_data/benchmark/fix_fasta_header/{project}.benchmark.txt",
    singularity: 
        "workflow/containers/image/python.3.12.2.debian.sif"
    shell:
        """
        python ./workflow/shell/fix_fasta_headers.py \
            --input {input.input_fasta} \
            --output {output.input_fasta_fixed}
        """

rule translate_start_to_stop:
    input:
        input_fasta_fixed = "_data/antigene_search/{project}/{project}.fixed.fasta"
    output:
        aminoacid_fasta = temp("_data/antigene_search/{project}/{project}.start_to_stop.aminoacid.fasta")
    params:
        orffinder_executable = config["orffinder"]
    benchmark: "_data/benchmark/translate_start_to_stop/{project}.benchmark.txt",
    shell:
        '''
        time {params.orffinder_executable} \
            -in {input.input_fasta_fixed} \
            -out {output.aminoacid_fasta} \
            -s 1 -ml 30 -strand plus
        '''

rule translate_stop_to_stop:
    input:
        input_fasta = "_data/antigene_search/{project}/{project}.fixed.fasta"
    output:
        aminoacid_fasta = "_data/antigene_search/{project}/{project}.stop_to_stop.aminoacid.fasta"
    params:
    benchmark: "_data/benchmark/translate_stop_to_stop/{project}.benchmark.txt",
    singularity: 
        "workflow/containers/image/python.3.12.2.debian.sif"
    shell:
        """
        python ./workflow/shell/3_frame_translation.py \
            --input {input.input_fasta} \
            --output {output.aminoacid_fasta}
        """


rule add_PE:
    input:
        aminoacid_fasta = lambda wildcards: (
            f"_data/antigene_search/{wildcards.project}/{wildcards.project}.{wildcards.translation_mode}.aminoacid.fasta"
            if get_search(wildcards.project).input_fasta
            else get_search(wildcards.project).input_aa_fasta
        )
    output:
        aminoacid_fasta_PE_changed = temp("_data/antigene_search/{project}/{project}.{translation_mode}.aminoacid_PEchanged.fasta")
    benchmark: "_data/benchmark/add_PE/{project}.{translation_mode}.benchmark.txt",
    singularity:
        "workflow/containers/image/python.3.12.2.debian.sif"
    shell:
        '''
        python ./workflow/shell/add_PE.py \
            --input {input.aminoacid_fasta} \
            --output {output.aminoacid_fasta_PE_changed} \
            --verbose
        '''


rule construct_database:
    input:
        aminoacid_fasta_PE_changed = "_data/antigene_search/{project}/{project}.{translation_mode}.aminoacid_PEchanged.fasta",
        uniprot = config["reference_proteome"]
    output:
        database_for_msfragger = "_data/antigene_search/{project}/final_msfragger_database.{project}.{translation_mode}.fasta"
    params:
        project = lambda wildcards: wildcards.project
    benchmark: "_data/benchmark/construct_database/{project}.{translation_mode}.benchmark.txt",
    singularity:
        "workflow/containers/image/fragpipe.22.0.ubuntu.sif"
    group:
        "fragpipe_steps"
    shell:
        '''
        work_dir=$(pwd)
        mkdir ./_data/antigene_search/{params.project}/tmp
        cd ./_data/antigene_search/{params.project}/tmp
        /fragpipe_bin/fragPipe-22.0/fragpipe/tools/Philosopher/philosopher-v5.1.1 workspace --init
        /fragpipe_bin/fragPipe-22.0/fragpipe/tools/Philosopher/philosopher-v5.1.1 database \
            --custom $work_dir/{input.aminoacid_fasta_PE_changed} \
            --add {input.uniprot} \
            --contam
        cd $work_dir
        mv ./_data/antigene_search/{params.project}/tmp/*.fasta.fas {output.database_for_msfragger}
        rm -r ./_data/antigene_search/{params.project}/tmp
        '''


rule run_Fragpipe:
    input:
        database_for_msfragger = "_data/antigene_search/{project}/final_msfragger_database.{project}.{translation_mode}.fasta",
        immunopeptidomics_data = lambda wildcards: get_search(wildcards.project).immunopeptidomics_data,
        workflow_template = lambda wildcards: f"workflow/shell/template_{get_search(wildcards.project).data_type}.workflow"
    output:
        workflow = "_data/antigene_search/{project}/{project}.{translation_mode}.workflow",
        psm_tsv = "_data/antigene_search/{project}/fragpipe_workdir.{project}.{translation_mode}/{project}/psm.tsv"
    params:
        project = lambda wildcards: wildcards.project,
        fdr = lambda wildcards: get_search(wildcards.project).fdr_for_ip,
        grouped_fdr = lambda wildcards: get_search(wildcards.project).grouped_fdr,
        data_type = lambda wildcards: get_search(wildcards.project).data_type,
        fragpipe_workdir = "_data/antigene_search/{project}/fragpipe_workdir.{project}.{translation_mode}",
        fragpipe_tools_folder = config["fragpipe_tools_folder"],
        tmp_dir = "tmp"
    threads:
        40
    resources:
        mem_mb = lambda wildcards, attempt: min(MAX_RAM_MB, 96000 + (attempt * 32000)),
        runtime = 120,
    benchmark: "_data/benchmark/run_Fragpipe/{project}.{translation_mode}.benchmark.txt",
    singularity:
        "workflow/containers/image/fragpipe.22.0.ubuntu.sif"
    group:
        "fragpipe_steps"
    shell:
        '''
        mkdir -p {params.tmp_dir}
        export _JAVA_OPTIONS="-Djava.io.tmpdir=/tmp"
        ls {input.immunopeptidomics_data}
        mkdir -p {params.fragpipe_workdir}
        sed -e "s|^database.db-path=.*|database.db-path={input.database_for_msfragger}|" \
            -e "s|^phi-report.filter=.*|phi-report.filter=--sequential --prot 1{params.grouped_fdr} --pep {params.fdr}|" \
            "{input.workflow_template}" > "{output.workflow}"
        ls {input.immunopeptidomics_data} | awk -v proj="{params.project}" -v ipd="{input.immunopeptidomics_data}" -v dtype="{params.data_type}"\
            '{{print ipd "/" $0 "\t" proj "\t\t" dtype}}' > "_data/antigene_search/{params.project}/{params.project}.manifest"
        time /fragpipe_bin/fragPipe-22.0/fragpipe/bin/fragpipe --headless \
            --config-tools-folder {params.fragpipe_tools_folder} \
            --workflow {output.workflow} \
            --manifest "_data/antigene_search/{params.project}/{params.project}.manifest" \
            --workdir {params.fragpipe_workdir}
        if [ "{params.data_type}" = "DIA" ]; then
            mkdir -p {params.fragpipe_workdir}/{params.project}
            cp {params.fragpipe_workdir}/psm.tsv {params.fragpipe_workdir}/{params.project}/psm.tsv
        fi
        '''


rule create_pep_file:
    input:
        psm_tsv = "_data/antigene_search/{project}/fragpipe_workdir.{project}.{translation_mode}/{project}/psm.tsv",
    output:
        pep = "_data/antigene_search/{project}/fragpipe_postprocessing/{project}.{translation_mode}.pep"
    params:
        project = lambda wildcards: wildcards.project,
    benchmark: "_data/benchmark/create_pep_file/{project}.{translation_mode}.benchmark.txt",
    singularity:
        "workflow/containers/image/netmhcpan.4.1.ubuntu.sif"
    shell:
        '''
        mkdir -p _data/antigene_search/{params.project}/fragpipe_postprocessing
        python3.6 ./workflow/shell/create_pep_file.py \
            --input {input.psm_tsv} \
            --output _{output.pep}
        '''

rule run_netMHCpan:
    input:
        pep = "_data/antigene_search/{project}/fragpipe_postprocessing/{project}.{translation_mode}.pep",
        hlas = lambda wildcards: get_search(wildcards.project).hla_txt
    output:
        xls = "_data/antigene_search/{project}/fragpipe_postprocessing/{project}.{translation_mode}.NetMHCpan_out.xls"
    params:
        project = lambda wildcards: wildcards.project
    resources:
        runtime = 120
    benchmark: "_data/benchmark/run_netMHCpan/{project}.{translation_mode}.benchmark.txt",
    singularity:
        "workflow/containers/image/netmhcpan.4.1.ubuntu.sif"
    shell:
        '''
        hlas_line=$(<{input.hlas})
        /usr/local/bin/netMHCpan-4.1/netMHCpan -a $hlas_line \
            -p {input.pep} \
            -xls -xlsfile {output.xls} > /dev/null
        '''

rule run_GibbsCluster:
    input:
        pep = "_data/antigene_search/{project}/fragpipe_postprocessing/{project}.{translation_mode}.pep",
        hlas = lambda wildcards: get_search(wildcards.project).hla_txt
    output:
        gibbs_csv = "_data/antigene_search/{project}/fragpipe_postprocessing/{project}.{translation_mode}.GibbsCluster_out.csv"
    params:
        project = lambda wildcards: wildcards.project
    benchmark: "_data/benchmark/run_GibbsCluster/{project}.{translation_mode}.benchmark.txt",
    singularity:
        "workflow/containers/image/gibbscluster.2.0.ubuntu.sif"
    shell:
        '''
        hlas_line=$(<{input.hlas})
        num_hlas=$(awk -F',' '{{print NF}}' <<< "$hlas_line")
        echo "$num_hlas"

        /gibbsCluster/gibbscluster-2.0/bin/gibbs_cluster_1.2.2_DB.Linux_x86_64 \
            -g $num_hlas \
            -trash \
            {input.pep} > {output.gibbs_csv}
        '''


rule fp_output_postprocessing:
    input:
        psm_tsv = "_data/antigene_search/{project}/fragpipe_workdir.{project}.{translation_mode}/{project}/psm.tsv",
        hlas = lambda wildcards: get_search(wildcards.project).hla_txt,
        netMHCpan_xls = "_data/antigene_search/{project}/fragpipe_postprocessing/{project}.{translation_mode}.NetMHCpan_out.xls",
        GibbsCluster_csv = "_data/antigene_search/{project}/fragpipe_postprocessing/{project}.{translation_mode}.GibbsCluster_out.csv",
        hla_la_cryptic = "_data/HLA_ligand_atlas/HLA_la_reported_cryptic_peptides.csv"
    output:
        csv = "_data/antigene_search/{project}/fragpipe_postprocessing/Summary.{project}.{translation_mode}.csv"
    params:
        project = lambda wildcards: wildcards.project,
        fdr = lambda wildcards: get_search(wildcards.project).fdr_for_ip,
        output_folder = lambda wildcards: f"_data/antigene_search/{wildcards.project}/fragpipe_postprocessing/",
        translation_mode = lambda wildcards: wildcards.translation_mode,
    benchmark: "_data/benchmark/fp_output_postprocessing/{project}.{translation_mode}.benchmark.txt",
    singularity:
        "workflow/containers/image/python.3.12.2.debian.sif"
    shell:
        '''
        hlas_line=$(<{input.hlas})
        python ./workflow/shell/fp_output_post_processing.py \
            --input_tsv {input.psm_tsv} \
            --netMHCpan_xls {input.netMHCpan_xls} \
            --GibbsCluster_csv {input.GibbsCluster_csv} \
            --sample {params.project} \
            --hla $hlas_line \
            --output_dir {params.output_folder} \
            --search_engine Fragpipe \
            --fdr {params.fdr} \
            --translation_mode {params.translation_mode} \
            --hla_la_cryptic {input.hla_la_cryptic} > /dev/null
        '''